name: Locust Performance Test

on:
  push:
    branches: [ main ]

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Locust
      run: |
        pip install locust

    - name: Run Locust Test
      run: |
       locust -f locustfile.py --headless -u 5 -r 1 -t 15s --host=https://reqres.in || true

