name: security_scan
on:
  push:
    branches: [ "main" ]     
  pull_request:
    branches: [ "main" ]    

jobs:

  zap-baseline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "https://fitnessapi.onrender.com"  
          rules_file_name: ".zap/rules.tsv"

          cmd_options: "-a -T 180"


  snyk-scan:
    runs-on: ubuntu-latest
    needs: zap-baseline           

    permissions:
      contents: read
      security-events: write      

    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@v4
      - name: Snyk Open Source Scan
        uses: snyk/actions/scan@v4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          fail-on: all                
          sarif-file-output: true     
          args: "--all-projects"      

